### ISSUE TITLE
QUESTION: How to store or share password?

### ISSUE THREAD

**Issue by dheimoz** [garbados/crypt#2]
Hello @garbados 

Great work you have been doing. Kudos for this library.

One question that I always have regarding encryption is, what is the best way to store or use the password text to encrypt and decrypt?

I assume that working on node you only have to use environment variables, but I wonder if there are betters approaches. PKI sounds good, but it becomes cumbersome very fast for end users.

I wonder if you have found a better way.

Thanks.

**Comment by garbados** [comment]
You never want to store the password, of course. You want to hash it so that even if an attacker retrieves the hash, they won't be able to determine the password. I've written this gist [here](https://gist.github.com/garbados/29ca945d5964ef85e7936804c23edb9d) as an example of how to salt and hash a password so as to store it safely in a database.

Does that help? Let me know if you have more questions, or if I've misunderstood your inquiry :)

**Comment by dheimoz** [comment]
Thanks @garbados Diana. Yes this helps!!!!!
And once again, super thanks for the great gist.
